import CONSTANTES_JSON from './constantes.json';

export const CONSTANTES = CONSTANTES_JSON;
export default CONSTANTES_JSON;

// Re-export agrupados por dominio para acceso directo y autocompletado
export const CONSTANTES_FINANCIERO = CONSTANTES_JSON.FINANCIERO;
export const CONSTANTES_ACADEMICO = CONSTANTES_JSON.ACADEMICO;
export const CONSTANTES_ROLES = CONSTANTES_JSON.ROLES;
export const CONSTANTES_DOCUMENTOS = CONSTANTES_JSON.DOCUMENTOS_IDENTIDAD;
export const CONSTANTES_MATRICULAS = CONSTANTES_JSON.MATRICULAS;
export const CONSTANTES_CONVIVENCIA = CONSTANTES_JSON.CONVIVENCIA;
export const CONSTANTES_FILTROS = CONSTANTES_JSON.FILTROS;
