export enum RoleCodigo {
  SUPERADMIN = 'SUPERADMIN',
  RECTOR = 'RECTOR',
  COORDINADOR = 'COORDINADOR',
  DOCENTE = 'DOCENTE',
  ESTUDIANTE = 'ESTUDIANTE',
  ACUDIENTE = 'ACUDIENTE',
  SECRETARIA = 'SECRETARIA',
  PSICORIENTADOR = 'PSICORIENTADOR',
  CONTADOR = 'CONTADOR',
  BIBLIOTECARIO = 'BIBLIOTECARIO',
  SERVICIOS_GENERALES = 'SERVICIOS_GENERALES',
}

export enum EstadoGeneral {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  BLOQUEADO = 'BLOQUEADO',
  PENDIENTE = 'PENDIENTE',
  ELIMINADO = 'ELIMINADO',
}

export enum TipoDocumento {
  CC = 'CC',
  TI = 'TI',
  CE = 'CE',
  RC = 'RC',
  PEP = 'PEP',
  PPT = 'PPT',
  PASAPORTE = 'PASAPORTE',
}

export enum DesempenoDecreto1290 {
  SUPERIOR = 'SUPERIOR',
  ALTO = 'ALTO',
  BASICO = 'BASICO',
  BAJO = 'BAJO',
}

export enum EstadoMatricula {
  PREMATRICULA = 'PREMATRICULA',
  MATRICULADO = 'MATRICULADO',
  RETIRADO = 'RETIRADO',
  GRADUADO = 'GRADUADO',
  ANULADO = 'ANULADO',
}

export enum EstadoCuentaCobro {
  PENDIENTE = 'PENDIENTE',
  PAGADO = 'PAGADO',
  PARCIAL = 'PARCIAL',
  VENCIDO = 'VENCIDO',
  ANULADO = 'ANULADO',
}

export enum MedioPago {
  PSE = 'PSE',
  TARJETA_CREDITO = 'TARJETA_CREDITO',
  TARJETA_DEBITO = 'TARJETA_DEBITO',
  EFECTIVO = 'EFECTIVO',
  TRANSFERENCIA_BANCARIA = 'TRANSFERENCIA_BANCARIA',
  CONSIGNACION = 'CONSIGNACION',
}

export enum TipoFaltaLey1620 {
  TIPO_I = 'TIPO_I',
  TIPO_II = 'TIPO_II',
  TIPO_III = 'TIPO_III',
}

export enum CategoriaFlujo {
  ACADEMICO = 'ACADEMICO',
  FINANCIERO = 'FINANCIERO',
  DISCIPLINARIO = 'DISCIPLINARIO',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
  RECURSOS_HUMANOS = 'RECURSOS_HUMANOS',
}

export enum TipoAccionEtapa {
  REVISION_SIMPLE = 'REVISION_SIMPLE',
  APROBACION = 'APROBACION',
  FIRMA_DIGITAL_OTP = 'FIRMA_DIGITAL_OTP',
  CARGA_DOCUMENTO = 'CARGA_DOCUMENTO',
  VALIDACION_SECRETARIA = 'VALIDACION_SECRETARIA',
}

export enum TipoFirma {
  TRAZO_DIGITAL = 'TRAZO_DIGITAL',
  CERTIFICADO_DIGITAL = 'CERTIFICADO_DIGITAL',
  OTP_SMS = 'OTP_SMS',
  OTP_EMAIL = 'OTP_EMAIL',
  BIOMETRICA = 'BIOMETRICA',
}

export enum EstadoInstanciaFlujo {
  INICIADO = 'INICIADO',
  EN_TRAMITE = 'EN_TRAMITE',
  APROBADO_FINAL = 'APROBADO_FINAL',
  RECHAZADO = 'RECHAZADO',
  ANULADO = 'ANULADO',
}

export enum TipoImportacion {
  COLEGIOS = 'COLEGIOS',
  ESTUDIANTES = 'ESTUDIANTES',
  MATRICULAS = 'MATRICULAS',
  DOCENTES = 'DOCENTES',
  CALIFICACIONES = 'CALIFICACIONES',
  NOTAS_1290 = 'NOTAS_1290',
  CARTERA_PENSIONES = 'CARTERA_PENSIONES',
  TESORERIA = 'TESORERIA',
  USUARIOS = 'USUARIOS',
}

export enum PlanColegio {
  BASICO = 'BASICO',
  ESTANDAR = 'ESTANDAR',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}
